const deck = [
  {
    emoji: "♦️",
    value: 2,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_2.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 3,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_3.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 4,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_4.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 5,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_5.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 6,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_6.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 7,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_7.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 8,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_8.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 9,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_9.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 10,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_10.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 10,
    face: "jack",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_J.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 10,
    face: "queen",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_Q.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 10,
    face: "king",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_K.png?raw=true",
  },
  {
    emoji: "♦️",
    value: 11,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/diamonds_A.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 2,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_2.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 3,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_3.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 4,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_4.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 5,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_5.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 6,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_6.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 7,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_7.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 8,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_8.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 9,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_9.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 10,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_10.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 10,
    face: "jack",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_J.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 10,
    face: "queen",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_Q.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 10,
    face: "king",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_K.png?raw=true",
  },
  {
    emoji: "♥️",
    value: 11,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/hearts_A.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 2,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_2.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 3,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_3.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 4,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_4.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 5,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_5.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 6,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_6.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 7,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_7.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 8,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_8.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 9,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_9.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 10,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_10.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 10,
    face: "jack",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_J.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 10,
    face: "queen",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_Q.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 10,
    face: "king",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_K.png?raw=true",
  },
  {
    emoji: "♣️",
    value: 11,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/clubs_A.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 2,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_2.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 3,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_3.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 4,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_4.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 5,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_5.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 6,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_6.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 7,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_7.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 8,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_8.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 9,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_9.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 10,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_10.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 10,
    face: "jack",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_J.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 10,
    face: "queen",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_Q.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 10,
    face: "king",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_K.png?raw=true",
  },
  {
    emoji: "♠️",
    value: 11,
    face: "none",
    img: "https://github.com/hanhaechi/playing-cards/blob/master/spades_A.png?raw=true",
  },
];

export default deck;
